"""Public contracts for reusable Trend Strategy v2 tooling."""

from .canonical import canonical_bytes, canonical_data, canonical_json, content_hash
from .contracts import (
    ArtifactKind,
    ArtifactRecord,
    ArtifactRetentionPolicy,
    CandidateEvaluation,
    CheckResult,
    ComparisonMode,
    DerivedMetricManifest,
    EvaluationProfile,
    EvaluationRun,
    ExecutionStatus,
    GateRule,
    MetricDefinition,
    MetricDirection,
    MetricMode,
    NormalizationMethod,
    ParetoObjective,
    SortRule,
    StrategyRunManifest,
    StrategyRunSpec,
    WeightedCandidateView,
)
from .evaluation import METRIC_ENGINE_VERSION, epsilon_pareto, evaluate_saved_runs, evaluate_strategy_runs
from .artifact_schemas import (
    ArtifactSchemaError,
    BEHAVIOR_METADATA_SCHEMA_VERSION,
    DAILY_PORTFOLIO_CURVE_SCHEMA_VERSION,
    ROBUSTNESS_SUMMARY_SCHEMA_VERSION,
    ROLLING_METRICS_SCHEMA_VERSION,
    YEARLY_METRICS_SCHEMA_VERSION,
    validate_behavior_metadata,
    validate_daily_portfolio_curve,
    validate_robustness_summary,
    validate_rolling_metrics,
    validate_yearly_metrics,
)
from .behavior import BEHAVIOR_ENGINE_VERSION, behavior_similarity, deduplicate_behaviors, generate_behavior_metadata
from .calculation import (
    DEFAULT_ROLLING_WINDOWS,
    DERIVED_METRICS_SCHEMA_VERSION,
    METRIC_CALCULATION_ENGINE_VERSION,
    METRIC_DEFINITION_VERSION,
    calculate_absolute_metrics,
    calculate_benchmark_relative_metrics,
    calculate_metric_artifact,
    calculation_settings,
    exact_common_date_curves,
    generate_rolling_metrics,
    generate_yearly_metrics,
    robustness_metrics,
)
from .integration import SavedRunEvaluationResult, calculate_and_evaluate_saved_runs
from .metrics import (
    METRIC_REGISTRY,
    EvaluationProfileValidationError,
    MetricValueRepresentationError,
    metric_registry,
    metrics_from_portfolio_summaries,
    validate_evaluation_profile,
    validate_metric_value,
)
from .profiles import load_evaluation_profile, load_evaluation_profiles
from .result_store import LocalResultStore, ResultStore
from .terminology import load_terminology_source, validate_terminology_source

__all__ = [
    "ArtifactKind",
    "ArtifactSchemaError",
    "ArtifactRecord",
    "ArtifactRetentionPolicy",
    "CandidateEvaluation",
    "CheckResult",
    "ComparisonMode",
    "DerivedMetricManifest",
    "EvaluationProfile",
    "EvaluationProfileValidationError",
    "EvaluationRun",
    "ExecutionStatus",
    "GateRule",
    "LocalResultStore",
    "METRIC_ENGINE_VERSION",
    "METRIC_CALCULATION_ENGINE_VERSION",
    "METRIC_DEFINITION_VERSION",
    "METRIC_REGISTRY",
    "MetricDefinition",
    "MetricDirection",
    "MetricMode",
    "MetricValueRepresentationError",
    "NormalizationMethod",
    "ParetoObjective",
    "ResultStore",
    "SortRule",
    "StrategyRunManifest",
    "StrategyRunSpec",
    "WeightedCandidateView",
    "SavedRunEvaluationResult",
    "BEHAVIOR_ENGINE_VERSION",
    "BEHAVIOR_METADATA_SCHEMA_VERSION",
    "DAILY_PORTFOLIO_CURVE_SCHEMA_VERSION",
    "YEARLY_METRICS_SCHEMA_VERSION",
    "ROLLING_METRICS_SCHEMA_VERSION",
    "ROBUSTNESS_SUMMARY_SCHEMA_VERSION",
    "DERIVED_METRICS_SCHEMA_VERSION",
    "DEFAULT_ROLLING_WINDOWS",
    "canonical_bytes",
    "canonical_data",
    "canonical_json",
    "content_hash",
    "epsilon_pareto",
    "calculate_absolute_metrics",
    "calculate_and_evaluate_saved_runs",
    "calculate_benchmark_relative_metrics",
    "calculate_metric_artifact",
    "calculation_settings",
    "exact_common_date_curves",
    "generate_behavior_metadata",
    "generate_rolling_metrics",
    "generate_yearly_metrics",
    "behavior_similarity",
    "deduplicate_behaviors",
    "robustness_metrics",
    "evaluate_saved_runs",
    "evaluate_strategy_runs",
    "load_evaluation_profile",
    "load_evaluation_profiles",
    "load_terminology_source",
    "metric_registry",
    "metrics_from_portfolio_summaries",
    "validate_terminology_source",
    "validate_evaluation_profile",
    "validate_metric_value",
    "validate_behavior_metadata",
    "validate_daily_portfolio_curve",
    "validate_robustness_summary",
    "validate_rolling_metrics",
    "validate_yearly_metrics",
]
